name: Deploy to PWS
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git Config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      - name: Push to PWS
        env:
          PWS_REPO_URL: https://${{ secrets.PWS_USERNAME }}:${{ secrets.PWS_PASSWORD }}@${{ secrets.PWS_HOST }}
        run: |
          git remote add pws $PWS_REPO_URL
          git branch -M master
          git config --global http.postBuffer 5242
          git push pws master
